### PR TITLE
[TECH DEBT] New session endpoint

### PR DESCRIPTION
**Pull request by tochman**
PT: Not added as a chore

* adds spec for user session

### CODE REVIEW

**Comment by faraznaeem** [comment]
This needs to be reviewed by team members

**Comment by julieahlquist** [comment]
We'd like to keep this. Created a chore for this in Pivotal Tracker: https://www.pivotaltracker.com/story/show/168040011

**Review by sethnejame — APPROVED** [review]
This looks good to me.  Test is specific, code is properly formatted, one ```expect``` per it block, and a general ```describe``` block that logs the user in before all subsequent tests.  Would like to merge this however we don't have the ability to merge here.

**Review by julieahlquist — APPROVED** [review]
We'd like to keep this straightforward and required. Link to chore for this in Pivotal Tracker: https://www.pivotaltracker.com/story/show/168040011

**Pull request merged**
